apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-access-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent-access-controller
subjects:
  - kind: ServiceAccount
    name: agent-access-controller
    namespace: agent-access-control-system
